<a href="https://colab.research.google.com/github/nmningmei/Deep_learning_fMRI_EEG/blob/master/7_2_simulation_of_statistical_learning_of_triplets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction

# Let's generate some sequences of the triplets

In [0]:
import numpy as np
import pandas as pd
from collections import Counter

## The following generation of unique triplet items could be generalized to any number of unique items

In [0]:
# createing a list of random numbers from 1 to any
np.random.seed(12345) # set up a random seed
random12 = np.arange(1,28) # from 1 to 27
np.random.shuffle(random12)
random12 = random12.reshape(-1,3)
random12


array([[24,  9, 11],
       [19, 13, 22],
       [ 4, 14, 16],
       [20, 17, 21],
       [ 1,  7,  8],
       [12, 23, 15],
       [18, 25, 27],
       [26, 10,  5],
       [ 2,  6,  3]])

In [0]:
T_pos = {key:val for key,val in zip("ABC",random12)}
converting_map = {key:val for key,val in zip("ABC",np.arange(1,4))}

In [0]:
n_trials = 1500
n_repeats = 24
trials = np.zeros((n_trials,n_repeats*len(converting_map.keys()),3))
labels = np.zeros((n_trials,n_repeats*len(converting_map.keys())))

## let's make a loop to get one trial of sequence

In [0]:

try:
    trial = []
    counting = {key:n_repeats for key in T_pos.keys()}
    for ii in range(int(1e3)):
        
        if ii == 0:
            trial.append(np.random.choice(list(T_pos.keys())))
        
        elif ii > 0:
            last_pick = trial[ii - 1]
            pick_list = list(T_pos.keys())
            pick_list.remove(last_pick)
            pick_proba = np.array([counting[item] for item in pick_list])
            pick_proba = pick_proba / np.sum(pick_proba)
            trial.append(np.random.choice(pick_list,p = pick_proba))
        
        if len(trial) >= 4:
            focus = trial[-4:]
            group1 = focus[:2]
            group2 = focus[2:]
            if group1 == group2:
                trial[ii] = [item for item in list(T_pos.keys()) if (item != trial[ii - 1]) and (item != trial[ii - 2])][0]
            else:
                pass
        temp_counting = dict(Counter(trial))
        for key in temp_counting.keys():
            counting[key] = 24 - temp_counting[key]
        
except Exception as ex:
    print(ex)
    print(Counter(trial))

probabilities contain NaN
Counter({'A': 24, 'C': 24, 'B': 24})


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:15: RuntimeWarning: invalid value encountered in true_divide
  from ipykernel import kernelapp as app


### As we rerun the cell above several times and then we would get something like `Counter({'B': 24, 'C': 24, 'A': 24})` and that is what we want. Since this works, let's make it a function

In [0]:
def generate_1_trial():
    try:
        trial = []
        counting = {key:n_repeats for key in T_pos.keys()}
        for ii in range(int(1e3)):

            if ii == 0:
                trial.append(np.random.choice(list(T_pos.keys())))

            elif ii > 0:
                last_pick = trial[ii - 1]
                pick_list = list(T_pos.keys())
                pick_list.remove(last_pick)
                pick_proba = np.array([counting[item] for item in pick_list])
                pick_proba = pick_proba / np.sum(pick_proba)
                trial.append(np.random.choice(pick_list,p = pick_proba))

            if len(trial) >= 4:
                focus = trial[-4:]
                group1 = focus[:2]
                group2 = focus[2:]
                if group1 == group2:
                    trial[ii] = [item for item in list(T_pos.keys()) if (item != trial[ii - 1]) and (item != trial[ii - 2])][0]
                else:
                    pass
            temp_counting = dict(Counter(trial))
            for key in temp_counting.keys():
                counting[key] = 24 - temp_counting[key]

    except Exception as ex:
        print(f"get {ex}, so repeat the process")
    return trial

### the reason I make this process a funtion is because I want to repeatedly calling this function until I get what I want, which is one trial of sequences

In [0]:
for _ in range(int(1e6)):
    trial = generate_1_trial()
    occurrence = dict(Counter(trial))
    occurrence = np.array([value for key,value in occurrence.items()])
    if all(occurrence == 24):
        print('done')
        break
print(Counter(trial),
     np.array(trial))
    

get probabilities are not non-negative, so repeat the process
get probabilities contain NaN, so repeat the process
get probabilities are not non-negative, so repeat the process
get probabilities contain NaN, so repeat the process
done
Counter({'B': 24, 'A': 24, 'C': 24}) ['B' 'A' 'C' 'A' 'B' 'A' 'C' 'B' 'A' 'B' 'C' 'B' 'A' 'B' 'C' 'A' 'C' 'B'
 'C' 'A' 'C' 'B' 'C' 'A' 'C' 'B' 'A' 'C' 'B' 'A' 'B' 'C' 'A' 'B' 'C' 'A'
 'C' 'B' 'A' 'C' 'A' 'B' 'A' 'C' 'B' 'C' 'A' 'B' 'C' 'B' 'A' 'C' 'B' 'C'
 'A' 'C' 'B' 'C' 'A' 'B' 'A' 'C' 'B' 'A' 'B' 'C' 'B' 'A' 'C' 'A' 'B' 'A']


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:15: RuntimeWarning: invalid value encountered in true_divide
  from ipykernel import kernelapp as app


### works well, let's start to generate many many trials

In [0]:
for_view = []
for n_trial_ in range(n_trials):
    for _ in range(int(1e6)):
        trial = generate_1_trial()
        occurrence = dict(Counter(trial))
        occurrence = np.array([value for key,value in occurrence.items()])
        if all(occurrence == 24):
            print('done')
            break
    trials[n_trial_,:,:] = [T_pos[item] for item in trial]
    labels[n_trial_,:] = [converting_map[item] for item in trial]
    for_view.append(trial)
for_view = np.array(for_view)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:15: RuntimeWarning: invalid value encountered in true_divide
  from ipykernel import kernelapp as app
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:15: RuntimeWarning: divide by zero encountered in true_divide
  from ipykernel import kernelapp as app


get probabilities contain NaN, so repeat the process
done
get probabilities contain NaN, so repeat the process
done
get probabilities contain NaN, so repeat the process
done
get probabilities contain NaN, so repeat the process
done
get probabilities contain NaN, so repeat the process
done
get probabilities contain NaN, so repeat the process
get probabilities contain NaN, so repeat the process
get probabilities contain NaN, so repeat the process
get probabilities contain NaN, so repeat the process
get probabilities contain NaN, so repeat the process
get probabilities contain NaN, so repeat the process
done
get probabilities contain NaN, so repeat the process
get probabilities contain NaN, so repeat the process
get probabilities are not non-negative, so repeat the process
get probabilities contain NaN, so repeat the process
get probabilities contain NaN, so repeat the process
get probabilities contain NaN, so repeat the process
get probabilities are not non-negative, so repeat the proces

### Let's randomly pick one of the trials and see if there are violations

In [0]:
idx_pick = np.random.choice(n_trials)
print(for_view[idx_pick])

['C' 'A' 'C' 'B' 'C' 'A' 'B' 'C' 'B' 'A' 'C' 'A' 'B' 'C' 'A' 'B' 'C' 'A'
 'C' 'B' 'C' 'A' 'B' 'A' 'C' 'B' 'C' 'A' 'B' 'C' 'B' 'A' 'B' 'C' 'B' 'A'
 'B' 'C' 'B' 'A' 'B' 'C' 'B' 'A' 'C' 'A' 'B' 'C' 'B' 'A' 'C' 'A' 'B' 'A'
 'C' 'B' 'A' 'C' 'A' 'B' 'C' 'A' 'B' 'C' 'A' 'C' 'B' 'A' 'C' 'A' 'B' 'A']


# the recurrent modeling part 1: supervised machine learning

In [0]:
import tensorflow as tf
from tensorflow.keras import (models,
                              layers,
                              optimizers,
                              regularizers,
                              losses,
                              metrics)
from sklearn.utils import shuffle

## First, we split the data into train (N = 1000), validation (N = 250), and test (N = 250)

In [0]:
sequences = trials.copy()
labels = labels.copy()

sequences, labels = shuffle(sequences,labels)

In [0]:
sequences_train,labels_train = sequences[:1000],labels[:1000]
sequences_valid,labels_valid = sequences[1000:1250],labels[1000:1250]
sequences_test,labels_test = sequences[1250:],labels[1250:]
print(sequences_train.shape,sequences_valid.shape,sequences_test.shape)
sequences_dict = {"train":sequences_train,
                  "valid":sequences_valid,
                  "test":sequences_test}
labels_dict = {"train":labels_train,
                  "valid":labels_valid,
                  "test":labels_test}

(1000, 72, 3) (250, 72, 3) (250, 72, 3)


## Second, we need to check the uniqueness of the sequential orders that do not overlap among train,validation, and test

In [0]:
converter = {key:val for key,val in zip(np.arange(1,4),"ABC")}

In [0]:
label_tran = {"train":set(),"valid":set(),"test":set()}
for key in label_tran.keys():
    for row in labels_dict[key]:
        temp = []
        for item in row:
            temp.append(converter[item])
        special = "".join(temp)
        label_tran[key].add(special)

In [0]:
for key,value in label_tran.items():
    print(f"{key} has {len(value)}")

train has 1000
valid has 250
test has 250


there is no repeated sequence order between train and validation

In [0]:
label_tran['train'].intersection(label_tran['valid'])

set()

there is no repeated sequence order between train and test

In [0]:
label_tran['train'].intersection(label_tran['test'])

set()

there is no repeated sequence order between test and validation

In [0]:
label_tran['test'].intersection(label_tran['valid'])

set()

## now, we define the RNN model

In [0]:
def build_RNN_model(batch_size = 10,drop = True,activation = 'softmax'):
    inputs = layers.Input(shape = sequences_train.shape[1:],
                          batch_size = batch_size,
                         name = 'inputs')
    RNN,state,seq = layers.LSTM(units = sequences_train.shape[1],
                                return_state = True,
                                return_sequences = True,
                                name = "RNN1")(inputs)
    RNN_2 = layers.LSTM(units = sequences_train.shape[1],
                        return_state = False,
                        return_sequences = True,
                        name = "RNN2")([RNN,state,seq])
    if drop:
        RNN_2 = layers.Dropout(0.5,name = "dropout")(RNN_2)
    outputs = layers.TimeDistributed(layers.Dense(3,name = 'outputs'))(RNN_2)
    outputs = layers.Activation(activation,name =activation)(outputs)
    RNN_model = models.Model(inputs,outputs,name = "RNN")
    
    print(RNN_model.summary())
    return RNN_model

In [0]:
RNN_model = build_RNN_model()

W0627 04:47:34.374790 139911995357056 deprecation.py:506] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


Model: "RNN"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
inputs (InputLayer)             [(10, 72, 3)]        0                                            
__________________________________________________________________________________________________
RNN1 (LSTM)                     [(10, 72, 72), (10,  21888       inputs[0][0]                     
__________________________________________________________________________________________________
RNN2 (LSTM)                     (10, 72, 72)         41760       RNN1[0][0]                       
                                                                 RNN1[0][1]                       
                                                                 RNN1[0][2]                       
________________________________________________________________________________________________

## process the labels: one-hot encoding

In [0]:
labels_one_hot = {}
for key,values in labels_dict.items():
    temp = np.zeros(sequences_dict[key].shape)
    for ii,row in enumerate(values):
        for jj,item in enumerate(row):
            k = np.zeros(3)
            k[int(item - 1)] = 1
            temp[ii,jj,:] = k
    labels_one_hot[key] = np.array(temp)

In [0]:
batch_size = 10
RNN_model = build_RNN_model(batch_size=batch_size)
RNN_model.compile(optimizer = optimizers.Adam(lr = 1e-4),
                  loss = losses.MSE,
                  metrics = [metrics.kld])
n_epochs = 10
RNN_model.fit(sequences_dict['train'],
              labels_one_hot['train'],
              epochs = n_epochs,
              batch_size = batch_size,
              validation_data = (sequences_dict['valid'],
                                 labels_one_hot['valid']),
              )

Model: "RNN"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
inputs (InputLayer)             [(10, 72, 3)]        0                                            
__________________________________________________________________________________________________
RNN1 (LSTM)                     [(10, 72, 72), (10,  21888       inputs[0][0]                     
__________________________________________________________________________________________________
RNN2 (LSTM)                     (10, 72, 72)         41760       RNN1[0][0]                       
                                                                 RNN1[0][1]                       
                                                                 RNN1[0][2]                       
________________________________________________________________________________________________

W0627 04:48:22.718860 139911995357056 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Epoch 1/10
1000/1000 [==============================] - 21s 21ms/sample - loss: 0.2157 - kullback_leibler_divergence: 1.0712 - val_loss: 0.1882 - val_kullback_leibler_divergence: 0.9513
Epoch 2/10
1000/1000 [==============================] - 19s 19ms/sample - loss: 0.1489 - kullback_leibler_divergence: 0.7826 - val_loss: 0.0761 - val_kullback_leibler_divergence: 0.4836
Epoch 3/10
1000/1000 [==============================] - 19s 19ms/sample - loss: 0.0400 - kullback_leibler_divergence: 0.2899 - val_loss: 0.0086 - val_kullback_leibler_divergence: 0.1177
Epoch 4/10
1000/1000 [==============================] - 20s 20ms/sample - loss: 0.0098 - kullback_leibler_divergence: 0.1095 - val_loss: 0.0034 - val_kullback_leibler_divergence: 0.0609
Epoch 5/10
1000/1000 [==============================] - 20s 20ms/sample - loss: 0.0051 - kullback_leibler_divergence: 0.0691 - val_loss: 0.0019 - val_kullback_leibler_divergence: 0.0408
Epoch 6/10
1000/1000 [==============================] - 20s 20ms/sampl

In [0]:
preds_valid = RNN_model.predict(sequences_dict['valid'],batch_size=batch_size)
preds_test = RNN_model.predict(sequences_dict['test'],batch_size=batch_size)


In [0]:
for a,b in zip(labels_one_hot['valid'].reshape(-1,3),preds_valid.reshape(-1,3)):
    print(f"one hot label = {a} probability = {b}")

one hot label = [0. 0. 1.] probability = [0.0617759  0.13046296 0.80776113]
one hot label = [0. 1. 0.] probability = [0.02442594 0.9482131  0.02736098]
one hot label = [0. 0. 1.] probability = [0.00730836 0.01314086 0.9795507 ]
one hot label = [1. 0. 0.] probability = [0.9815072  0.01257288 0.00591994]
one hot label = [0. 1. 0.] probability = [0.00298723 0.9880922  0.00892055]
one hot label = [0. 0. 1.] probability = [0.00287337 0.00433878 0.9927879 ]
one hot label = [1. 0. 0.] probability = [0.9876579  0.00844717 0.00389488]
one hot label = [0. 0. 1.] probability = [0.00396017 0.01003479 0.986005  ]
one hot label = [0. 1. 0.] probability = [0.00725726 0.9882465  0.00449628]
one hot label = [1. 0. 0.] probability = [0.9941204  0.00332917 0.00255042]
one hot label = [0. 0. 1.] probability = [0.00319344 0.00764206 0.98916453]
one hot label = [1. 0. 0.] probability = [0.98581856 0.01008182 0.00409962]
one hot label = [0. 1. 0.] probability = [0.00260387 0.9893566  0.00803952]
one hot labe

In [0]:
for a,b in zip(labels_one_hot['test'].reshape(-1,3),preds_test.reshape(-1,3)):
    print(f"one hot label = {a} probability = {b}")

one hot label = [0. 1. 0.] probability = [0.06598686 0.84062207 0.09339103]
one hot label = [0. 0. 1.] probability = [0.01042526 0.02129661 0.96827817]
one hot label = [0. 1. 0.] probability = [0.01209421 0.9767421  0.01116368]
one hot label = [1. 0. 0.] probability = [0.99096644 0.00529255 0.00374106]
one hot label = [0. 0. 1.] probability = [0.003527   0.00999907 0.9864739 ]
one hot label = [0. 1. 0.] probability = [0.00585364 0.9897115  0.00443491]
one hot label = [1. 0. 0.] probability = [0.9929382  0.00410923 0.0029526 ]
one hot label = [0. 1. 0.] probability = [0.00217767 0.9906087  0.00721363]
one hot label = [0. 0. 1.] probability = [0.00244101 0.00359945 0.99395955]
one hot label = [1. 0. 0.] probability = [0.98696566 0.00892854 0.00410586]
one hot label = [0. 1. 0.] probability = [0.00261637 0.9889113  0.00847235]
one hot label = [0. 0. 1.] probability = [0.00266861 0.00353972 0.99379164]
one hot label = [1. 0. 0.] probability = [0.98817945 0.00791283 0.00390772]
one hot labe

# the recurrent modeling part 2: unsupervised machine learning

## first we need make the copy of the inputs but recale them so that we could use the sigmoid function to learn the objective function. 

In [0]:
output_seq = {}
for key,value in sequences_dict.items():
    output_seq[key] = value / random12.max()


In [0]:
inputs = layers.Input(shape = sequences_train.shape[1:],batch_size=batch_size,name = 'inputs')
RNN1 = layers.LSTM(units=sequences_train.shape[1],
                   return_state = True,
                   return_sequences = True,
                   name = 'RNN1')(inputs)
RNN2 = layers.LSTM(units=sequences_train.shape[1],
                   return_state = False,
                   return_sequences = True,
                   name = 'RNN2')(RNN1)
drop = layers.Dropout(0.5,name = 'dropout')(RNN2)
outputs = layers.TimeDistributed(layers.Dense(3,activation = 'sigmoid',name = 'outputs'))(drop)
AE = models.Model(inputs,outputs,name = 'autoencoder')
print(AE.summary())
AE.compile(loss = losses.mse,
           optimizer = optimizers.Adam())
n_epochs = 10
AE.fit(output_seq['train'],
       output_seq['train'],
       epochs = n_epochs,
       shuffle = True,
       validation_data = (output_seq['valid'],output_seq['valid']),
       batch_size = batch_size,)

Model: "autoencoder"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
inputs (InputLayer)             [(10, 72, 3)]        0                                            
__________________________________________________________________________________________________
RNN1 (LSTM)                     [(10, 72, 72), (10,  21888       inputs[0][0]                     
__________________________________________________________________________________________________
RNN2 (LSTM)                     (10, 72, 72)         41760       RNN1[0][0]                       
                                                                 RNN1[0][1]                       
                                                                 RNN1[0][2]                       
________________________________________________________________________________________

In [0]:
preds_valid = AE.predict(output_seq['valid']) * random12.max()

In [0]:
for a,b in zip(sequences_dict['valid'].reshape(-1,3)[:10],preds_valid.reshape(-1,3)):
    print(a,b)

[ 4. 14. 16.] [ 4.723477 13.858792 16.512106]
[19. 13. 22.] [19.38434  12.667225 21.168278]
[ 4. 14. 16.] [ 3.6548529 14.150481  16.60416  ]
[24.  9. 11.] [24.408989  9.014205 11.325532]
[19. 13. 22.] [19.189814 12.911525 21.98977 ]
[ 4. 14. 16.] [ 3.8610122 14.035915  16.247581 ]
[24.  9. 11.] [24.203608  9.126398 11.361943]
[ 4. 14. 16.] [ 4.073495 13.960417 16.224947]
[19. 13. 22.] [19.097614 13.000046 22.14283 ]
[24.  9. 11.] [24.346638  9.119807 11.303586]
